#!/bin/bash

ZGT_DIR=$(dirname $(dirname $(readlink -m ${0})))

cd $ZGT_DIR
for f in $(find . \( -name "zgtask*.c" ! -name "*_selftest.c" \) -exec readlink -f {} \;);do
    uncrustify -c uncrustify.cfg $f --no-backup
done

#for f in $(find . \( -name "zgtask*.h" ! -name "*_classes.h" ! -name "*_library.h" \) -exec readlink -f {} \;);do
#    uncrustify -c uncrustify.cfg $f --no-backup
#done
