/*  =========================================================================
    zgtask - ZGTASK wrapper

    Copyright (c) the Contributors as noted in the AUTHORS file.       
    This file is part of CZMQ, the high-level C binding for 0MQ:       
    http://czmq.zeromq.org.                                            
                                                                       
    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.           

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
    =========================================================================
*/

#ifndef zgtask_library_H_INCLUDED
#define zgtask_library_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <zyre.h>
#include <jansson.h>

//  ZGTASK version macros for compile-time API detection

#define ZGTASK_VERSION_MAJOR 0
#define ZGTASK_VERSION_MINOR 1
#define ZGTASK_VERSION_PATCH 0

#define ZGTASK_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define ZGTASK_VERSION \
    ZGTASK_MAKE_VERSION(ZGTASK_VERSION_MAJOR, ZGTASK_VERSION_MINOR, ZGTASK_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined LIBZGTASK_STATIC
#       define ZGTASK_EXPORT
#   elif defined LIBZGTASK_EXPORTS
#       define ZGTASK_EXPORT __declspec(dllexport)
#   else
#       define ZGTASK_EXPORT __declspec(dllimport)
#   endif
#else
#   define ZGTASK_EXPORT
#endif

//  Opaque class structures to allow forward references
typedef struct _zgtask_task_t zgtask_task_t;
#define ZGTASK_TASK_T_DEFINED
typedef struct _zgtask_net_t zgtask_net_t;
#define ZGTASK_NET_T_DEFINED
typedef struct _zgtask_tree_t zgtask_tree_t;
#define ZGTASK_TREE_T_DEFINED


//  Public API classes
#include "zgtask_task.h"
#include "zgtask_net.h"
#include "zgtask_tree.h"

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
